"""Classification enums for SHELXL cards.

These replace the magic strings proposed in the original edit plan so the
type checker can catch typos and non-exhaustive matches.  Members are
plain :class:`enum.Enum` values, deliberately *not* ``StrEnum``: the whole
point is to stop cards being compared against string literals.
"""

from __future__ import annotations

from enum import Enum, auto


class CardLifetime(Enum):
    r"""Whether a card is live input or inert output.

    SHELXL stops reading at ``END``.  Anything after it -- most commonly
    the ``SADI`` restraints generated by a bare ``SADI`` instruction,
    followed by the ``Q`` peak list -- is a record of the *previous*
    refinement that the program never reads back.

    Those generated lines also carry ``ACTA TABS`` part suffixes
    (``C1^a`` for PART 1, ``C1A^b`` for PART 2).  SHELXL itself notes in
    the emitted comment that this form "has not yet been implemented for
    input into SHELXL", so the names cannot be resolved against the atom
    list and must not be treated as references.
    """

    #: Before ``END``: a real instruction, editable and atom-linked.
    INPUT = auto()

    #: After ``END``: inert output.  Excluded from atom linking and
    #: validation, and preserved verbatim on write.
    POST_END_OUTPUT = auto()

    def __bool__(self) -> bool:
        """``True`` only for live input, so ``if card.lifetime:`` reads well."""
        return self is CardLifetime.INPUT


class AtomGrouping(Enum):
    """How a card's flat ``atoms`` list is grouped when an atom goes away.

    The list is stored flat, but SHELXL reads structure into it, and
    dropping a single name can leave a card that means something else
    entirely.
    """

    #: Independent names; drop just the one that went.
    FLAT = auto()

    #: ``DFIX``/``DANG``/``SADI``: "the first and second named atom, the
    #: third and fourth, ..." -- losing one name invalidates its partner,
    #: so the whole pair goes.
    PAIRS = auto()

    #: Plain ``SAME`` or ``SAME_<n>``: the list "is compared with the same
    #: number of atoms which follow the SAME instruction", so the
    #: counterpart is not on the card at all -- it is the run of atoms
    #: after it in the file.
    SAME_FOLLOWING_ATOMS = auto()

    #: ``SAME_<class>``: applies to every residue of that class instead,
    #: matching atoms by name and order.
    SAME_RESIDUE_CLASS = auto()


class AtomListSemantics(Enum):
    """What an *empty* atom list means for a card.

    Decided per instance at parse time, because it depends on whether the
    author wrote any atom names.  Getting this wrong is costly in both
    directions: 1217 files in the reference corpus carry a card that was
    authored empty on purpose.
    """

    #: Names were given. The only case a minimum atom count applies to.
    EXPLICIT = auto()

    #: ``ISOR``/``SIMU``/``DELU``/``RIGU``/``ANIS``/``BOND``/``CONF``
    #: with no names means "all non-hydrogen atoms". Letting an edited
    #: card reach this state would silently widen it to the whole
    #: structure, so such a card is removed rather than emptied.
    GLOBAL_WHEN_EMPTY = auto()

    #: A bare ``SADI``/``CONN``/``BLOC``/``OMIT`` is a different
    #: instruction altogether -- a bare ``SADI`` asks SHELXL to write the
    #: restraints derived from ``SAME`` after ``END``. These reference no
    #: atoms and are never atom-linked.
    DIRECTIVE_WHEN_EMPTY = auto()

    #: ``BUMP``/``DEFS``: the grammar has no atom list at all
    #: (``BUMP s``, ``DEFS sd sf su ss maxsof``).  Distinct from an
    #: *empty* list, which is an authoring choice about a card that
    #: could have named atoms; here there is nothing that could ever be
    #: emptied, so a minimum atom count must never be applied.
    NEVER_NAMES_ATOMS = auto()


class AfixDependency(Enum):
    """Where an ``AFIX`` group's pivot atom sits, from the ``n`` digit.

    The distinction decides who disappears with whom: a riding group
    depends on an atom *outside* its own bracket, while a rigid group's
    pivot is the first atom inside it.
    """

    #: ``n`` = 0, 1, 2 -- no positional dependency on another atom.
    NONE = auto()

    #: ``n`` = 3, 4 -- "ride on the previous non-riding atom", which
    #: precedes the ``AFIX`` card.
    RIDING = auto()

    #: ``n`` = 7, 8 -- ride on the preceding atom and rotate about its
    #: bond. Such a group runs "until the next AFIX with n not equal to 7".
    ROTATING = auto()

    #: ``n`` = 6, 9 -- "the next atom is the pivot atom of a new rigid
    #: group", so the pivot is inside the bracket.
    RIGID_PIVOT = auto()

    #: ``n`` = 5 -- a dependent atom of the enclosing rigid group.
    RIGID_DEPENDENT = auto()

    @classmethod
    def from_code(cls, mn: int | None) -> AfixDependency:
        """Classify an ``AFIX mn`` code.

        Only the last digit carries the constraint type; the leading
        digits select the geometry.
        """
        if mn is None:
            return cls.NONE
        return {
            3: cls.RIDING,
            4: cls.RIDING,
            5: cls.RIGID_DEPENDENT,
            6: cls.RIGID_PIVOT,
            7: cls.ROTATING,
            8: cls.ROTATING,
            9: cls.RIGID_PIVOT,
        }.get(abs(mn) % 10, cls.NONE)

    @property
    def pivot_is_outside_bracket(self) -> bool:
        """``True`` when the group depends on an atom before the card."""
        return self in (AfixDependency.RIDING, AfixDependency.ROTATING)


class AtomReferencingCard:
    """Shared classification for any card that names atoms.

    Restraints are not the only instructions that reference atoms:
    ``HFIX``, ``ANIS``, ``BOND``, ``MPLA``, ``CONN``, ``CONF``, ``BIND``,
    ``FREE`` and ``HTAB`` do too, and would be left pointing at deleted
    atoms if only restraints were maintained.

    Subclasses store their atoms in different shapes -- a flat ``atoms``
    list, or named fields such as ``FREE``'s ``atom1``/``atom2`` -- so
    :attr:`referenced_atoms` normalises access to them.
    """

    #: How the atom list is structured. See :class:`AtomGrouping`.
    ATOM_GROUPING: AtomGrouping = AtomGrouping.FLAT

    #: Fewest atoms the card still means something with.  Only consulted
    #: when :attr:`atom_semantics` is ``EXPLICIT``.
    MIN_ATOMS: int = 2

    #: What an empty atom list means for this card *class*.
    EMPTY_MEANS: AtomListSemantics = AtomListSemantics.EXPLICIT

    #: Whether the card is live input or inert post-``END`` output.
    lifetime: CardLifetime = CardLifetime.INPUT

    @property
    def referenced_atoms(self) -> list[str]:
        """Atom tokens this card names, in source order."""
        return list(getattr(self, 'atoms', []) or [])

    @property
    def atom_grouping(self) -> AtomGrouping:
        """How to interpret :attr:`referenced_atoms` for this instance."""
        return self.ATOM_GROUPING

    @property
    def atom_semantics(self) -> AtomListSemantics:
        """What this *instance*'s atom list means.

        A card that named atoms is ``EXPLICIT`` whatever its class; only
        one authored without names takes on the class meaning.
        """
        if self.referenced_atoms:
            return AtomListSemantics.EXPLICIT
        return self.EMPTY_MEANS

    @property
    def is_atom_linked(self) -> bool:
        """Whether this card takes part in atom bookkeeping.

        Excludes inert post-``END`` output, cards whose empty list means
        "everything", and bare directives.
        """
        return (self.lifetime is CardLifetime.INPUT
                and self.atom_semantics is AtomListSemantics.EXPLICIT)
