"""Classification enums for SHELXL cards.

These replace the magic strings proposed in the original edit plan so the
type checker can catch typos and non-exhaustive matches.  Members are
plain :class:`enum.Enum` values, deliberately *not* ``StrEnum``: the whole
point is to stop cards being compared against string literals.
"""

from __future__ import annotations

from enum import Enum, auto


class CardLifetime(Enum):
    """Whether a card is live input or inert output.

    SHELXL stops reading at ``END``.  Anything after it -- most commonly
    the ``SADI`` restraints generated by a bare ``SADI`` instruction,
    followed by the ``Q`` peak list -- is a record of the *previous*
    refinement that the program never reads back.

    Those generated lines also carry ``ACTA TABS`` part suffixes
    (``C1^a`` for PART 1, ``C1A^b`` for PART 2).  SHELXL itself notes in
    the emitted comment that this form "has not yet been implemented for
    input into SHELXL", so the names cannot be resolved against the atom
    list and must not be treated as references.
    """

    #: Before ``END``: a real instruction, editable and atom-linked.
    INPUT = auto()

    #: After ``END``: inert output.  Excluded from atom linking and
    #: validation, and preserved verbatim on write.
    POST_END_OUTPUT = auto()

    def __bool__(self) -> bool:
        """``True`` only for live input, so ``if card.lifetime:`` reads well."""
        return self is CardLifetime.INPUT
