name: publish
on:
  push:
    tags:
      - '*'
jobs:
  tests:
    uses: ./.github/workflows/unit-tests.yml
  build:
    runs-on: ubuntu-latest
    # Build and publish are gated on successful tests.
    needs:
      - tests

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.14"

      - run: uv build

      - uses: actions/upload-artifact@v7
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    needs:
      - build
    environment:
      name: publish

    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: release-dists
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/